INSERT INTO MEMBER(MEMBER_ID,PASSWORD,MEMBER_NAME,DT_REG,UDT_REG) values (1,'1234','문태환',NULL,NULL )
INSERT INTO MEMBER(MEMBER_ID,PASSWORD,MEMBER_NAME,DT_REG,UDT_REG) values (2,'1234','사과씨앗',NULL,NULL )
INSERT INTO MEMBER(MEMBER_ID,PASSWORD,MEMBER_NAME,DT_REG,UDT_REG) values (3,'1234','사과나무',NULL,NULL )

INSERT INTO BOARD(BOARD_ID,MEMBER_ID,TITLE,CONTENT,DT_REG,UDT_REG) values (1,1,'메인 게시판 게시물 첫번쨰','첫번쨰 게시물','2021-04-22 10:11',NULL)
INSERT INTO BOARD(BOARD_ID,MEMBER_ID,TITLE,CONTENT,DT_REG,UDT_REG) values (2,1,'메인 게시판 게시물 첫번쨰','첫번쨰 게시물','2021-04-22',NULL)
INSERT INTO BOARD(BOARD_ID,MEMBER_ID,TITLE,CONTENT,DT_REG,UDT_REG) values (3,1,'메인 게시판 게시물 첫번쨰','첫번쨰 게시물','2021-04-22',NULL)

INSERT INTO BOARD(BOARD_ID,MEMBER_ID,TITLE,CONTENT,DT_REG,UDT_REG) values (4,2,'메인 게시판 게시물 두번쨰','두번쨰 게시물','2021-04-22',NULL)
INSERT INTO BOARD(BOARD_ID,MEMBER_ID,TITLE,CONTENT,DT_REG,UDT_REG) values (5,2,'메인 게시판 게시물 두번쨰','두번쨰 게시물','2021-04-22',NULL)
INSERT INTO BOARD(BOARD_ID,MEMBER_ID,TITLE,CONTENT,DT_REG,UDT_REG) values (6,2,'메인 게시판 게시물 두번쨰','두번쨰 게시물','2021-04-22',NULL)

INSERT INTO BOARD(BOARD_ID,MEMBER_ID,TITLE,CONTENT,DT_REG,UDT_REG) values (7,3,'메인 게시판 게시물 세번쨰','세번쨰 게시물','2021-04-22',NULL)
INSERT INTO BOARD(BOARD_ID,MEMBER_ID,TITLE,CONTENT,DT_REG,UDT_REG) values (8,3,'메인 게시판 게시물 세번쨰','세번쨰 게시물','2021-04-22',NULL)
INSERT INTO BOARD(BOARD_ID,MEMBER_ID,TITLE,CONTENT,DT_REG,UDT_REG) values (9,3,'메인 게시판 게시물 세번쨰','세번쨰 게시물','2021-04-22',NULL)

INSERT INTO BOARD(BOARD_ID,MEMBER_ID,TITLE,CONTENT,DT_REG,UDT_REG) values (10,1,'메인 게시판 게시물 네번쨰','네번쨰 게시물','2021-04-22',NULL)
INSERT INTO BOARD(BOARD_ID,MEMBER_ID,TITLE,CONTENT,DT_REG,UDT_REG) values (11,1,'메인 게시판 게시물 네번쨰','네번쨰 게시물','2021-04-22',NULL)
INSERT INTO BOARD(BOARD_ID,MEMBER_ID,TITLE,CONTENT,DT_REG,UDT_REG) values (12,1,'메인 게시판 게시물 네번쨰','네번쨰 게시물','2021-04-22',NULL)

INSERT INTO BOARD(BOARD_ID,MEMBER_ID,TITLE,CONTENT,DT_REG,UDT_REG) values (13,2,'메인 게시판 게시물 다섯번쨰','다섯번쨰 게시물','2021-04-22',NULL)
INSERT INTO BOARD(BOARD_ID,MEMBER_ID,TITLE,CONTENT,DT_REG,UDT_REG) values (14,2,'메인 게시판 게시물 다섯번쨰','다섯번쨰 게시물','2021-04-22',NULL)
INSERT INTO BOARD(BOARD_ID,MEMBER_ID,TITLE,CONTENT,DT_REG,UDT_REG) values (15,2,'메인 게시판 게시물 다섯번쨰','다섯번쨰 게시물','2021-04-22',NULL)